services:
  db:
    image: mongo:latest
    container_name: messenger_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data:/data/db
      - ./init.js:/docker-entrypoint-initdb.d/init.js  # Подключение скрипта инициализации
    ports:
      - 27017:27017