services:
  db:
    image: mongo:latest
    container_name: messenger_mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: messenger_db
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./data:/data/db
#      - ./init.sh:/docker-entrypoint-initdb.d/init.sh  # Подключение скрипта инициализации
    ports:
      - 27017:27017