spring:
  application:
    name: messenger

  profiles:
    active: dev

  data:
    mongodb:
      host: localhost
      port: 27017
      database: messenger_db
      username: messenger_user
      password: password


server:
  port: 8080

logging:
  level:
    org.springframework: INFO
    com.example: DEBUG
