spring:
  application:
    name: messenger # ??? ??????????

  profiles:
    active: dev # ???????? ??????? (dev, prod ? ?.?.)

  data:
    mongodb:
      host: localhost
      port: 27017
      database: messenger_db
      username: ${MONGODB_USERNAME:default_username} # ?????? ???????? ?? ?????????
      password: ${MONGODB_PASSWORD:default_password} # ?????? ???????? ?? ?????????

server:
  port: 8080 # ????, ?? ??????? ????? ???????? ??????????

logging:
  level:
    org.springframework: INFO
    com.example: DEBUG # ??????????? ??? ????? ???????
